CREATE SCHEMA demoshop;

CREATE TABLE statistics(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST,
    homeViewCount INT NOT NULL DEFAULT 0
);

CREATE TABLE admin(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST,
    username VARCHAR(30) NOT NULL,
    password VARCHAR(30) NOT NULL
);

CREATE TABLE product(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST,
    categoryId INT UNSIGNED NOT NULL,
    SKU VARCHAR(30) NOT NULL UNIQUE KEY,
    title VARCHAR(30) NOT NULL,
    brand VARCHAR(30) NOT NULL,
    price FLOAT NOT NULL,
    shortDescription VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    image BLOB NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT 0,
    featured BOOLEAN NOT NULL DEFAULT 0,
    viewCount INT UNSIGNED NOT NULL DEFAULT 0,
    FOREIGN KEY (categoryId) REFERENCES category(id)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE category(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST,
    parentId INT UNSIGNED DEFAULT NULL,
    code VARCHAR(30) NOT NULL UNIQUE KEY,
    title VARCHAR(30) NOT NULL,
    description VARCHAR(255) NOT NULL,
    FOREIGN KEY (parentId) REFERENCES category(id)
    ON DELETE RESTRICT ON UPDATE CASCADE
);